### ISSUE TITLE
location of attachment is not updated

### ISSUE THREAD

**Issue by olesendan** [jalvesaq/zotcite#10]
Hi Jalvesaq

I'm having problems oping attached files to citations in zotcite.

my setup is now
archlinux
zotero with plugins zotfile, betterbibtex etc.
neovim with nvim-r, zotcite etc.

in zotfile I've changed the location of files to a custom place, so files are linked. zotero can open the files.

in neovim, I kan insert the citations. If I try to open the attached files i'm getting a messaged that it can't find the file.
in the message the location of the file is the standard location of storage in zotero.

Do you think its possible to make an varible in zotcite something like this
let $ZoteroStorage = "~/path/to/storage/"
In custom location, flies can be placed in subfolders

Greetings from denmark
Dan Olesen

**Comment by jalvesaq** [comment]
The code to find the file associated with a reference is located at `autoload/zotcite.vim`. So, we could set a Vim variable instead of an environment variable. But, before doing that, I need to know how the file path is stored by Zotero. Could you, please, give me an example of the attachment field. For example, if I press `<Leader>za` over a specific citation key in a Markdown document, I get:

```
attachment: ['BX99SUA7:storage:Clark et al. - 2008 - Relative Income, Happiness, and Utility An Explan.pdf']
```

**Comment by jalvesaq** [comment]
I've improved the code for opening attachments. Could you, please, check if it works now?
