### ISSUE TITLE
How to Use Citation Key Alternative

### ISSUE THREAD

**Issue by TheCedarPrince** [jalvesaq/zotcite#17]
Hi @jalvesaq ,

I am a little confused about how to use `citation.vim` alongside `zotcite.vim` in order to use actual citation keys generated in a `.bib` file. I tried following the documentation, but was unclear on what to do. What should I do to my `.vimrc` to make this work? Here is the documentation I was trying to follow:

```vim
" You can also use citation.vim (https://github.com/rafaqz/citation.vim) to insert
" the citation keys if you set the Zotero key to
" be the first part of the citation key followed by a hashtag. Example: 

let g:citation_vim_key_format = "{zotero_key}#{author}_{date}"

```

**Comment by jalvesaq** [comment]
Zotcite doesn't support the use of bib files. The bibliographic data is extracted directly from Zotero's sqlite database. I will remove the reference to `citation.vim` because I'm not using it. I know that I tried to use use `citation.vim` to insert citation keys and it worked, but I don't remember how I had configured it.

**Comment by TheCedarPrince** [comment]
Gotcha. Thanks @jalvesaq! I may have to shift back over to `citation.vim` sadly because I need access to a bib file and its citation keys. I was hoping with `zotcite.vim` and `citation.vim` I could have the best of both worlds with the ease that your project provides in Vim - truly a super nice experience! - and the power of `citation.vim`.

I may come back to this project more in the future as I really like the idea! Take care. :smiley:

**Comment by jalvesaq** [comment]
My goal with zotcite is to avoid the need for intermediaries between Zotero and Vim (that is, bib files) because the bib file becomes outdated whenever I change any reference field in Zotero. As an alternative, zotcite provides is the command `:Zrefs` which inserts the current bibliographic data as YAML code suitable for inclusion in the YAML header of the markdown document.

**Comment by TheCedarPrince** [comment]
That makes sense. However, you can fix that by just having Zotero keep your bib file up to date.

But yea, I discovered `vim-pandoc` which seems a much better fit to my use case. Thanks for the good project though.
