### ISSUE TITLE
Dependent on other vim plugins?

### ISSUE THREAD

**Issue by chunyunma** [jalvesaq/zotcite#21]
This may seem a silly question, but I am wondering if zotcite requires installation other plugins, 
such as citation.vim and unite.vim?  
In the "README" under "installation", no other vim plugins were mentioned. 
However, there is no mentioning in the zotcite's documentation of how zotcite accesses 
zotero's database, 
which seems incredible if zotcite knows where a user stores all the references...

**Comment by jalvesaq** [comment]
Zotcite doesn't depend on other plugins. I cited them to let users explore them and choose what better fits their needs.

Zotero registers user's preferences at `~/.zotero/zotero/profiles.ini` and Zotcite reads the file to know where the references are stored.

**Comment by chunyunma** [comment]
Thank you so much for the quick reply!  This is very interesting. 
I installed the plugin, but the <C-x><C-o> did not work as expected. 
For example, I started typing `@ca..` in a file `test.md`, and then pressed <C-x><C-o>, 
in the status bar, it says "-- Omi completion (^O^N^P) Pattern not found". 
I tried typing a few other author's name, but the result did not change. 
I went to look for the zotero's file you mentioned. 
Apparently, it is located in `~/Library/Application\ Support/Zotero/profiles.ini`.
I am on a mac os + neovim

I also tested with a minimal config for vim, but the outcome remained the same. 

```
"*****************************************************************************
"" Basic/global settings
"*****************************************************************************

" Turn on syntax highlighting
syntax on

" Turn on line number
set number

" Ignore case in searches
set ignorecase
set smartcase

" Global settings for tab
set tabstop=2
set shiftwidth=2
set noexpandtab

" use indentation scripts located in the `indent` folder of vim installation
filetype plugin indent on
" Change Leader and LocalLeader keys: 
let maplocalleader = ','
let mapleader = ';'

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif


"*****************************************************************************
"" mappings
"*****************************************************************************
" edit my vimrc file
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" source my vimrc file
nnoremap <leader>sv :source $MYVIMRC<cr>


"*****************************************************************************
"" abbreviations
"*****************************************************************************
" iab @@ mcypsy@gmail.com
iab !installnvimcom! renv::install("~/.local/share/nvim/plugged/Nvim-R/R/nvimcom_x")
iab <expr> dts strftime("%FT%T%z")



"*****************************************************************************
"" Aesthetics
"*****************************************************************************
" use Tomorrow-Night as colour-scheme
" colorscheme base16-default-dark
if filereadable(expand("~/.vimrc_background"))
	let base16colorspace=256
	source ~/.vimrc_background
endif

"*****************************************************************************
"" Plug install packages
"*****************************************************************************
" ----- Specify a directory for plugins -----
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.local/share/nvim/plugged')

" List of plugins.
" Make sure you use single quotes

" To disable a plugin temporarily
" Plug 'foo/bar', { 'on': [] }
" Shorthand notation

" Zotcite to connect zotero with vim
Plug 'jalvesaq/zotcite'

" Nvim-R is the communicator between vim and R
Plug 'jalvesaq/Nvim-R'  


" Initialize plugin system
call plug#end()

"*****************************************************************************
"" Customize plugin behaviour
"*****************************************************************************
" Nvim-R -------
" Change default to no saving work image and no startup message
" This only affects the behaviour of R inside vim
let R_args = ['--no-save', '--quiet']
" quick insert chunk delimiter in rmd with two instead of one backticks
let R_rmdchunk = '``'
let R_assign = 3

"*****************************************************************************
"" Python venv
"*****************************************************************************
" This is where I install python pkg related to nvim
" including jedi and pynvim 
let g:python3_host_prog='/Users/chunyun/.pyenv/versions/neovim/bin/python'
let g:python_host_prog='/Users/chunyun/.pyenv/versions/neovim-py2/bin/python'

"******************************************************************************
"" autocmd
"******************************************************************************
" shortcut to commend out lines
:autocmd FileType python     nnoremap <buffer> <localleader>c I# <esc>
:autocmd FileType r          nnoremap <buffer> <localleader>c I# <esc>
:autocmd FileType rmd        nnoremap <buffer> <localleader>c I# <esc>
:autocmd FileType vim        nnoremap <buffer> <localleader>c I" <esc>
```

**Comment by jalvesaq** [comment]
It now checks if the file '~/Library/Application Support/Zotero/profiles.ini' exists. Does it work now?

**Comment by chunyunma** [comment]
It still does not work. 
However, here is some interesting finding:

In an empty `md` or `Rmd` file, when I type `@c..` and press `<c-x><c-o>`, 
I still get the old message "-- Omi completion (^O^N^P) Pattern not found". 
However, if I include a yaml header in the file such as the following:

```
---
bibliography: [book.bib]
---
```

Then pressing `<c-x><c-o>` will produce the following error message:

```
Error detected while processing function CompleteR[20]..RmdNonRCompletion[21]..zotcite#CompleteBib[39]..provider#python3#Call:
line   18:
Error invoking 'python_eval' on channel 6 (python3-script-host):
error caught in request handler 'python_eval ['ZotCite.GetMatch("ca", "/Users/chunyun/tmp/test.Rmd")']':
Traceback (most recent call last):
  File "/Users/chunyun/.pyenv/versions/neovim/lib/python3.9/site-packages/pynvim/plugin/script_host.py", line 171, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
NameError: name 'ZotCite' is not defined
Error detected while processing function CompleteR[20]..RmdNonRCompletion[21]..zotcite#CompleteBib:
line   40:
E714: List required
```

**Comment by jalvesaq** [comment]
When you include the `bibliography` field in the Yaml header, zotcite disables itself because I expected that users would be going to use another plugin to complete the citations.

**Comment by chunyunma** [comment]
That makes sense...
Sadly, the autocomplete still does not work 😿

**Comment by jalvesaq** [comment]
Unfortunately, I don't have access to any Mac system to replicate the bug and fix it.

**Comment by whytong** [comment]
I confirm that I have the same issue on a Linux system that says ``Omni completion (O^N^P) Pattern not found``.
My system:
>Vim version: 8.2.1897 from:  ppa:jonathonf/vim, complied with -python +python3 (Linux Mint has only vim 8.0)
>Python 3.7.7
>System: Linux Mint 19.3 Tricia
>Zotero 5.0.94
All required packages poppler, qt5 etc. installed.

Minimal VIMRC:
```
set nocompatible
" vim-plug
call plug#begin()
  Plug 'jalvesaq/zotcite', { 'for': 'markdown'}
  Plug 'iamcco/markdown-preview.nvim', {'do': { -> mkdp#util#install()}, 'for': ['markdown', 'vim-plug'] }
call plug#end()

" set zotcite
let $ZoteroSQLpath = '/home/whytong/Zotero/zotero.sqlite'
```
vim-plug.vim is in .vim/autoload/ folder.

What I found could be a hint of the issue is the following error message when I type ``:Zinfo`` it gives the following info:

``There is another omnifunc enabled: htmlcomplete#CompleteTags``

Same issue even if I disable ``markdown-preview.nvim``.

I got most of zotcite to work on WSL2/Ubuntu 20.04 with same vim 8.2.1897 (with many other plugins and configurations in VIMRC which probably overrode the omnifunc?) but there I run into another issue that I cannot choose from different references, only the first match ref is inserted even if I moves the cursor through the list of refs (through the up and down arrow keys). I did not notice this issue previously since I did not check the bibliography generated carefully.

**Comment by jalvesaq** [comment]
Even using both minimal vimrc and minimal init.vim, I can't replicate the issue on Ubuntu using either Vim (8.2.716) or Neovim (development version) or Neovim (0.4.4). In all of them, I get omni completion of citation keys if the first character in the pattern being completed is `@`  and HTML tag completion if it is `<`.

`:Zinfo` doesn't give any warning about other omni completion function, while
```
:echo b:non_z_omnifunc
```
outputs
```
htmlcomplete#CompleteTags
```

**Comment by whytong** [comment]
OK. Installed Neovim 0.4.4 on Linux Mint and I still have the same issue, with the same configuration.

Confirmed that `omnifunc` is set to `zotecite#CompleteBib` and `b:non_z_omnifunc=htmlcomplete#CompleteTags` on the working configuration whereas `omnifunc` set to `htmlcomplete#CompleteTags` in the ones I have troubles. There were a few discussions about this omnifunc previously, e.g. [issue #16](https://github.com/jalvesaq/zotcite/issues/16). The "htmlcomplete#CompleteTags" in defined in the `html.vim` in vim installation folder. And when I open a markdown file, it seems like the html.vim is loaded and overwrites the definition of `omnifunc` from `zotcite` (weird, how did this happen? Is it because the `syntax/markdown.vim` file has the definition of htmlUrl?

It turns out if I remove the `, {'for': 'markdown'}` in the vim-plug line for zotcite, the `i_Ctrl-X-Ctrl-O` is working, which happens to be omitted in my WSL2/Ubuntu vim configuration.

However, `:ZInfo` gives out an error message:
```
Error detected while processing function zotcite#info:
line    13:
E730: using List as a String
```
due to a fix on the banned word in issue [#26](https://github.com/jalvesaq/zotcite/issues/26)?

I still cannot choose from multiple references, only the first matched ref is inserted. Shall I open a new issue for this bug?

**Comment by jalvesaq** [comment]
I have fixed the last issue (using List as a String) two hours ago. Please, update zotcite and it should work.

Zotcite enables itself only for Markdown, Pandoc and RMarkdown. So, the argument `{'for': 'markdown'}` might be unnecessary.

**Comment by whytong** [comment]
Thank you. Yes, List as String fixed as promised.
