### ISSUE TITLE
Support for Latex File Type

### ISSUE THREAD

**Issue by naveedpash** [jalvesaq/zotcite#30]
Hi
Amazing plugin

Is it possible to that `<C-X><C-O>` can be made to work in latex document without having to type `@` but instead having to type `\cite{`?

**Comment by jalvesaq** [comment]
It would be possible to trigger omni completion of citation keys after "\cite.*{". Then, zotcite should overwrite the .bib file declared in the preamble of the LaTeX document. This feature would not be too complicated to implement for single LaTeX documents.

However, I'm no longer using LaTeX to write academic papers because it's difficult to convert to other formats. Now, I use LaTeX only to write pandoc templates to convert Markdown into PDF the way I want. So, I'm sorry, but someone else would have to do a push request for this feature to be implemented, and he or she should become responsible for maintaining the code.

**Comment by lervag** [comment]
[VimTeX](https://github.com/lervag/vimtex/) supports omni-completion of citations from `.bib` files. This can easily be integrated with Zotero by using a (automatic) export to `.bib` files. You should probably use the better-bibtex Zotero plugin. I do this myself. Notice also that VimTeX has a convenient context menu that allows to e.g. open a related pdf, and I've found this to work well with my Zotero library.

**Comment by jalvesaq** [comment]
Although I no longer use LaTeX, I can review a pull request for this, but not depending on better-bibtex. Since the export would be automatic, there is no need for fancy citation keys, and we can keep using Zotero's internal citation keys.

Zotcite also can open the PDF, but there is no harm in having overlapping features.

**Comment by jalvesaq** [comment]
I started adding support for Quarto documents. A bib file in the `/tmp` directory is overwritten each time that the output is generated. So, if someone wants to add support for LaTeX, the starting point would be the support for Quarto: https://github.com/jalvesaq/zotcite/commits/quarto

**Comment by jalvesaq** [comment]
It seems that nobody is going to develop LaTeX support... So, the best option if editing LaTeX directly is to use [VimTex](https://github.com/lervag/vimtex/). I don't know how zotcite could be useful in this case.

If the goal is to generate a LaTeX document from Quarto, these options might be useful:

```yaml
bibliography: refs-zotcite.bib
format:
  pdf:
    keep-tex: true
    cite-method: biblatex
```

See: https://quarto.org/docs/authoring/footnotes-and-citations.html#sec-biblatex
