### ISSUE TITLE
Can I configure the plugin so it shows Better BibTeX citation keys instead of `@AWYRRI2Y#Chomsky_1970` style keys?

### ISSUE THREAD

**Issue by MarcoCamilo** [jalvesaq/zotcite#63]
I've found this is the only plugin that effortlessly integrates citation keys with cmp autocompletion (of course, having cmp-zotcite installed). But personally I don't use the `@AWYRRI2Y#Chomsky_1970` style citation keys, but Better BibTeX citation keys. 

I'd love to see if there's any way I can configure the plugin, so that it searches the Better BibTeX citation keys either in my `.bib` or `.json` library files (or any way else). Is there anything to make this possible at the moment? 

Thanks in advance and thank you for the plugin.

**Comment by jalvesaq** [comment]
Please, see this: https://github.com/jalvesaq/zotcite/issues/60

I'm sorry, but I don't plan to implement integration with Better BibTeX. The goal of zotcite is to get information directly from Zotero's database, avoiding the need to manually export references from Zotero into bib files.

**Comment by jalvesaq** [comment]
Note:

Nvim-R completes citation keys in both `.Rnw` and `.Rmd` documents:

  - https://github.com/jalvesaq/Nvim-R/blob/master/R/bibcompl.vim
  - https://github.com/jalvesaq/Nvim-R/blob/master/R/bibtex.py

I'm not sure if it still works because I don't use it.

[vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) seems to do much more.

So, someone could use one of them as a starting point to develop a plugin that does what you need. I can't do it because it's a feature that I wouldn't use.
